SUBROUTINE EFT_PLESS_PW_FIT(R, L, S, J, TZ, V, CF, RF)
  IMPLICIT NONE
  DOUBLE PRECISION, PARAMETER :: HTC = 197.32697D0
  DOUBLE PRECISION, PARAMETER :: PI= 4.D0*DATAN(1.D0)
  
  INTEGER, INTENT(IN) :: L, S, J, TZ
  DOUBLE PRECISION, INTENT(IN) :: R
  DOUBLE PRECISION, INTENT(IN) :: CF, RF
  DOUBLE PRECISION, INTENT(OUT):: V(2,2)

  INTEGER :: T

  T = MOD(MOD(L+S, 2) + 1, 2)

  V = 0.D0
  IF ( T.EQ.0 .AND. S.EQ.0 ) THEN
    V(1,1) = CF*(-4*R**2 + 6*RF**2)/(DEXP(R**2/RF**2)*PI**1.5D0*RF**7)
  ENDIF
  V = V*HTC

  RETURN
END SUBROUTINE EFT_PLESS_PW_FIT