SUBROUTINE NUMEROV_HOMOGENOEUS(H, Y, F, YA, YB, N, IS_FORWARD)
IMPLICIT NONE
INTEGER, INTENT(IN) :: N
DOUBLE PRECISION, INTENT(IN) :: H, YA, YB, F(0:N)
DOUBLE PRECISION, DIMENSION(0:N), INTENT(INOUT) :: Y
LOGICAL, INTENT(IN), OPTIONAL :: IS_FORWARD
DOUBLE PRECISION, DIMENSION(0:N) :: FH

INTEGER :: I
LOGICAL :: FORWARD

IF (.NOT.PRESENT(IS_FORWARD)) THEN
  FORWARD = .TRUE.
ELSE
  FORWARD = IS_FORWARD
ENDIF

FH = H**2/12*F

IF (FORWARD) THEN
  Y(0) = YA
  Y(1) = YB

  DO I=2, N
    Y(I) = 2*Y(I-1)*(1 - 5*FH(I-1)) - Y(I-2)*(1 + FH(I-2))
    Y(I) = Y(I)/(1 + FH(I))
  ENDDO

ELSE
  Y(N)  = YA
  Y(N-1)= YB

  DO I = N-2 , 0, -1
    Y(I) = 2*Y(I+1)*(1 - 5*FH(I+1)) - Y(I+2)*(1 + FH(I+2))
    Y(I) = Y(I)/(1 + FH(I))
  ENDDO

ENDIF


END SUBROUTINE NUMEROV_HOMOGENOEUS