! FUNCTION TO COMPUTE THE CHI-SQUARED ERROR
FUNCTION CHI_SQUARED(C, R0, E_DATA, DELTA_DATA, NE, N) RESULT(CHI2)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: C, R0
  INTEGER, INTENT(IN) :: NE, N
  DOUBLE PRECISION, INTENT(IN) :: E_DATA(NE), DELTA_DATA(N)
  DOUBLE PRECISION :: DELTA_MODEL(N)
  DOUBLE PRECISION :: Y(NE)
  DOUBLE PRECISION :: CHI2
  INTEGER :: I

  ! COMPUTE THEORETICAL PHASE SHIFTS FOR GIVEN C AND R0
  CALL NUMEROV_SCATTERING_SINGLE_CHANNEL(E_DATA, Y, NE, 1, 0 ,1, -1, 0, C, R0, DELTA_MODEL)
  ! COMPUTE CHI-SQUARED
  CHI2 = ((DELTA_MODEL(1)-DELTA_DATA(1))/MIN(DELTA_DATA(1),DELTA_MODEL(1)))**2 &
        +((DELTA_MODEL(2)-DELTA_DATA(2))/MIN(DELTA_DATA(2),DELTA_MODEL(2)))**2*200 &
        +((DELTA_MODEL(3)-DELTA_DATA(3))/MIN(DELTA_DATA(3),DELTA_MODEL(3)))**2*10
  ! WRITE(*,*) C, R0, CHI2, DELTA_MODEL
END FUNCTION CHI_SQUARED

! COMPUTE NUMERICAL GRADIENT USING FINITE DIFFERENCES
SUBROUTINE COMPUTE_GRADIENT(C, R0, GRAD_C, GRAD_R0, E_DATA, DELTA_DATA, NE, N)
  IMPLICIT NONE
  DOUBLE PRECISION, INTENT(IN) :: C, R0
  INTEGER, INTENT(IN) :: N, NE
  DOUBLE PRECISION, INTENT(IN) :: E_DATA(NE), DELTA_DATA(N)
  DOUBLE PRECISION, INTENT(OUT) :: GRAD_C, GRAD_R0
  DOUBLE PRECISION, PARAMETER :: EPS = 1.0D-6
  DOUBLE PRECISION :: CHI0, CHI_C, CHI_R0
  DOUBLE PRECISION, EXTERNAL :: CHI_SQUARED

  CHI0 = CHI_SQUARED(C, R0, E_DATA, DELTA_DATA, NE, N)
  CHI_C = CHI_SQUARED(C + EPS, R0, E_DATA, DELTA_DATA, NE, N)
  CHI_R0 = CHI_SQUARED(C, R0 + EPS, E_DATA, DELTA_DATA, NE, N)

  GRAD_C = (CHI_C - CHI0) / EPS
  GRAD_R0 = (CHI_R0 - CHI0) / EPS
  ! write(*,*) GRAD_C, GRAD_R0
END SUBROUTINE COMPUTE_GRADIENT

! PERFORM GRADIENT DESCENT OPTIMIZATION
SUBROUTINE GRADIENT_DESCENT(C, R0, E_DATA, DELTA_DATA, NE, N, MAX_ITER, TOL, ALPHA)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NE, N, MAX_ITER
  DOUBLE PRECISION, INTENT(INOUT) :: C, R0
  DOUBLE PRECISION, INTENT(IN) :: E_DATA(N), DELTA_DATA(N), TOL, ALPHA
  DOUBLE PRECISION :: GRAD_C, GRAD_R0
  DOUBLE PRECISION :: CHI_SQUARED
  INTEGER :: ITER
  DOUBLE PRECISION :: CHI_MIN, C_MIN, R0_MIN, CHI

  CHI_MIN = 1.D99
  DO ITER = 1, MAX_ITER
      CALL COMPUTE_GRADIENT(C, R0, GRAD_C, GRAD_R0, E_DATA, DELTA_DATA, NE, N)
      CHI = CHI_SQUARED(C, R0, E_DATA, DELTA_DATA, NE, N)
      IF (CHI .LT. CHI_MIN) THEN
        CHI_MIN  = CHI
        C_MIN = C
        R0_MIN= R0
      ENDIF
      IF (MOD(ITER, MAX_ITER/20).EQ.0) &
          WRITE(*,*) "Done iteration: ", ITER, "GRAD: ", SQRT(GRAD_C**2 + GRAD_R0**2), &
              CHI, CHI_MIN
      
      IF (SQRT(GRAD_C**2 + GRAD_R0**2) < TOL) EXIT  ! CONVERGENCE CRITERION

      C = C - ALPHA * GRAD_C
      R0 = R0 - ALPHA * GRAD_R0
  END DO
  C = C_MIN
  R0= R0_MIN
  WRITE(*,*) "Iteration: ", ITER
  WRITE(*,*) "Grad value ", DCMPLX(GRAD_C, GRAD_R0) 
END SUBROUTINE GRADIENT_DESCENT
