SUBROUTINE POT_PW(IPOT, ILB, LEMP, EMCOUL, L, S, J, T1Z, T2Z, R, VPW, CF, RF, NCOEFF)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: IPOT, LEMP, L, S, J, T1Z, T2Z, NCOEFF
  LOGICAL, INTENT(INOUT) :: EMCOUL
  DOUBLE PRECISION, INTENT(IN) :: R
  DOUBLE PRECISION, INTENT(OUT):: VPW(2,2)
  INTEGER, INTENT(IN) :: ILB
  DOUBLE PRECISION, INTENT(IN) :: CF, RF
!
  INTEGER :: T
!
  T = MOD( MOD(L+S,2) + 1 , 2)
!
  SELECT CASE (IPOT)
  CASE (14)
    CALL AV14PW(LEMP, EMCOUL, L, S, J, T1Z, T2Z, R, VPW)
    RETURN
  CASE (18)
    CALL AV18PW(ILB, EMCOUL, L, S, J, T, T1Z, T2Z, R, VPW)
    RETURN
  CASE (19)
    CALL EFT_PLESS_PW(LEMP, ILB, L, S, J, T1Z, T2Z, R, VPW)
    RETURN
  CASE (20)
    CALL EFT_PLESS_PW_NEW(R, L, S, J, T1Z + T2Z, VPW)
    RETURN
  CASE (-1)
    CALL EFT_PLESS_PW_FIT(R, L, S, J, T1Z + T2Z, VPW, CF, RF, NCOEFF)
    RETURN
  CASE DEFAULT
    STOP "ERROR, POTENTIAL NOT FOUND"
  END SELECT
  RETURN

END SUBROUTINE POT_PW