name: Test Makefile on macOS

on:
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GSL, lapack and blas
        run: |
          brew install gsl openblas lapack gfortran
          echo "GSL, lapack and blas installed"
          
      - name: Ensure gfortran is linked
        run: |
          echo "Checking gfortran installation"
          which gfortran || echo "gfortran not found in PATH"
          if ! which gfortran; then
            echo "Linking gfortran manually"
            ln -s /usr/local/bin/gfortran-$(gcc --version | head -n 1 | awk '{print $3}') /usr/local/bin/gfortran || true
          fi
          gfortran --version
          
      - name: Verify Fortran Compiler
        run: |
          which gfortran
          gfortran --version


      - name: Set up PETSc
        run: |
          cd $HOME
          echo "Setting up PETSc"
          echo "Current directory: $(pwd)"
          echo "Current user: $(whoami)"
          echo "Current date: $(date)"
          echo "Current PATH: $PATH"
          git clone -b release https://gitlab.com/petsc/petsc.git petsc
          cd petsc
          ./configure --download-mpich --download-fblaslapack --download-make --with-fc=gfortran
          make all check
          echo "PETSc installed"

      - name: Test print_os
        run: |
          echo "Running print_os"
          make print_os
          echo "print_os completed"

      - name: Debug Directory
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Test Makefile
        run: |
          make config
          make all
          make run