name: Test Makefile on macOS

on:
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GSL, lapack, blas, and gfortran
        run: |
          brew install gsl openblas lapack gfortran
          brew link gcc
          echo "GSL, lapack, blas, and gfortran installed"

      - name: Ensure gfortran is in PATH
        run: |
          echo "Adding gfortran to PATH"
          export PATH="/opt/homebrew/bin:/opt/homebrew/Cellar/gcc/14.2.0_1/bin:$PATH"
          which gfortran || echo "gfortran not found in PATH"
          gfortran --version

      - name: Verify Fortran Compiler
        run: |
          echo "Verifying Fortran compiler"
          export PATH="/opt/homebrew/bin:/opt/homebrew/Cellar/gcc/14.2.0_1/bin:$PATH"
          which gfortran
          gfortran --version

      - name: Debug Homebrew Installation
        run: |
          echo "Listing Homebrew-installed files"
          ls -la /opt/homebrew/bin
          ls -la /opt/homebrew/Cellar/gcc/14.2.0_1/bin

      - name: Set up PETSc
        run: |
          cd $HOME
          echo "Setting up PETSc"
          export PATH="/opt/homebrew/bin:/opt/homebrew/Cellar/gcc/14.2.0_1/bin:$PATH"
          git clone -b release https://gitlab.com/petsc/petsc.git petsc
          cd petsc
          ./configure --download-mpich --download-fblaslapack --download-make
          make all check
          echo "PETSc installed"

      - name: Check directory PETSc
        run: |
          tree -d $HOME/petsc
          exit -1

      - name: Test print_os
        run: |
          echo "Running print_os"
          make print_os
          echo "print_os completed"

      - name: Debug Directory
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Test Makefile
        run: |
          make config
          make all
          make run