name: Test Makefile on Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PETSc
        run: |
          cd $HOME
          echo "Setting up PETSc"
          sudo apt-get update
          sudo apt-get install git
          mkdir petsc
          git clone -b release https://gitlab.com/petsc/petsc.git petsc
          git pull
          cd petsc
          ./configure --download-mpich --download-fblaslapack
          make all check

      - name: Test print_os
        run: |
          echo "Running print_os"
          make print_os
          echo "print_os completed"

      - name: Test Makefile
        run: |
          apt-get update
          make config
          make all
          make run