name: Test Makefile on Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GSL, lapack and blas
        run: |
          sudo apt-get install -y libgsl-dev liblapack-dev libblas-dev
          echo "GSL installed" 

      - name: Set up PETSc
        run: |
          cd $HOME
          echo "Setting up PETSc"
          echo "Current directory: $(pwd)"
          echo "Current user: $(whoami)"
          echo "Current date: $(date)"
          echo "Current PATH: $PATH"
          git clone -b release https://gitlab.com/petsc/petsc.git petsc
          cd petsc
          ./configure --download-mpich --download-fblaslapack
          make all check

      - name: Test print_os
        run: |
          echo "Running print_os"
          make print_os
          echo "print_os completed"

      - name: Debug Directory
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Test Makefile
        run: |
          make config
          make all
          make run